/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateVendorInput = {
  id?: string | null,
  vendorNumber: string,
  companyReportName: string,
  companyListingName: string,
  address1?: string | null,
  address2?: string | null,
  city?: string | null,
  state?: string | null,
  zipCode?: string | null,
  telephoneNum?: string | null,
  attention?: string | null,
  prepayment: boolean,
  prepaymentAmt: number,
};

export type CreateContractInput = {
  id?: string | null,
  contractNumber: string,
  contractType: ContractType,
  contractState: ContractState,
  vendorId: string,
  commodityId: string,
  quantity: number,
  contractPrice: number,
  salePrice?: number | null,
  terms?: string | null,
  weights?: string | null,
  basis?: string | null,
  remarks?: string | null,
  beginDate: string,
  endDate: string,
  dateSigned?: string | null,
  purchasedFrom?: string | null,
  soldTo?: string | null,
};

export enum ContractType {
  SALE = "SALE",
  PURCHASE = "PURCHASE",
}


export enum ContractState {
  ACTIVE = "ACTIVE",
  CLOSED = "CLOSED",
}


export type CreateTicketInput = {
  id?: string | null,
  contractId: string,
  ticketDate: string,
  fieldNum?: string | null,
  baleCount?: number | null,
  ticketNumber?: string | null,
  ladingNumber?: string | null,
  driver?: string | null,
  truckNumber?: string | null,
  grossWeight?: number | null,
  tareWeight?: number | null,
  netWeight?: number | null,
  netTons?: number | null,
};

export type CreateCompanyInfoInput = {
  id?: string | null,
  companyName: string,
  additionalName?: string | null,
  address1: string,
  address2?: string | null,
  city: string,
  state: string,
  zipCode: number,
  federalId?: string | null,
  telephoneNum?: string | null,
  faxNum?: string | null,
};

export type ModelCompanyInfoConditionInput = {
  companyName?: ModelStringInput | null,
  additionalName?: ModelStringInput | null,
  address1?: ModelStringInput | null,
  address2?: ModelStringInput | null,
  city?: ModelStringInput | null,
  state?: ModelStringInput | null,
  zipCode?: ModelIntInput | null,
  federalId?: ModelStringInput | null,
  telephoneNum?: ModelStringInput | null,
  faxNum?: ModelStringInput | null,
  and?: Array< ModelCompanyInfoConditionInput | null > | null,
  or?: Array< ModelCompanyInfoConditionInput | null > | null,
  not?: ModelCompanyInfoConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type UpdateCompanyInfoInput = {
  id: string,
  companyName?: string | null,
  additionalName?: string | null,
  address1?: string | null,
  address2?: string | null,
  city?: string | null,
  state?: string | null,
  zipCode?: number | null,
  federalId?: string | null,
  telephoneNum?: string | null,
  faxNum?: string | null,
};

export type DeleteCompanyInfoInput = {
  id?: string | null,
};

export type CreateCommodityInput = {
  id?: string | null,
  name: string,
  calculateCode: number,
  billingCode: number,
  poundsPerBushel?: number | null,
};

export type ModelCommodityConditionInput = {
  name?: ModelStringInput | null,
  calculateCode?: ModelIntInput | null,
  billingCode?: ModelIntInput | null,
  poundsPerBushel?: ModelIntInput | null,
  and?: Array< ModelCommodityConditionInput | null > | null,
  or?: Array< ModelCommodityConditionInput | null > | null,
  not?: ModelCommodityConditionInput | null,
};

export type UpdateCommodityInput = {
  id: string,
  name?: string | null,
  calculateCode?: number | null,
  billingCode?: number | null,
  poundsPerBushel?: number | null,
};

export type DeleteCommodityInput = {
  id?: string | null,
};

export type ModelVendorConditionInput = {
  vendorNumber?: ModelStringInput | null,
  companyReportName?: ModelStringInput | null,
  companyListingName?: ModelStringInput | null,
  address1?: ModelStringInput | null,
  address2?: ModelStringInput | null,
  city?: ModelStringInput | null,
  state?: ModelStringInput | null,
  zipCode?: ModelStringInput | null,
  telephoneNum?: ModelStringInput | null,
  attention?: ModelStringInput | null,
  prepayment?: ModelBooleanInput | null,
  prepaymentAmt?: ModelFloatInput | null,
  and?: Array< ModelVendorConditionInput | null > | null,
  or?: Array< ModelVendorConditionInput | null > | null,
  not?: ModelVendorConditionInput | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelFloatInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type UpdateVendorInput = {
  id: string,
  vendorNumber?: string | null,
  companyReportName?: string | null,
  companyListingName?: string | null,
  address1?: string | null,
  address2?: string | null,
  city?: string | null,
  state?: string | null,
  zipCode?: string | null,
  telephoneNum?: string | null,
  attention?: string | null,
  prepayment?: boolean | null,
  prepaymentAmt?: number | null,
};

export type DeleteVendorInput = {
  id?: string | null,
};

export type ModelContractConditionInput = {
  contractNumber?: ModelStringInput | null,
  contractType?: ModelContractTypeInput | null,
  contractState?: ModelContractStateInput | null,
  vendorId?: ModelIDInput | null,
  commodityId?: ModelIDInput | null,
  quantity?: ModelFloatInput | null,
  contractPrice?: ModelFloatInput | null,
  salePrice?: ModelFloatInput | null,
  terms?: ModelStringInput | null,
  weights?: ModelStringInput | null,
  basis?: ModelStringInput | null,
  remarks?: ModelStringInput | null,
  beginDate?: ModelStringInput | null,
  endDate?: ModelStringInput | null,
  dateSigned?: ModelStringInput | null,
  purchasedFrom?: ModelStringInput | null,
  soldTo?: ModelStringInput | null,
  and?: Array< ModelContractConditionInput | null > | null,
  or?: Array< ModelContractConditionInput | null > | null,
  not?: ModelContractConditionInput | null,
};

export type ModelContractTypeInput = {
  eq?: ContractType | null,
  ne?: ContractType | null,
};

export type ModelContractStateInput = {
  eq?: ContractState | null,
  ne?: ContractState | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type UpdateContractInput = {
  id: string,
  contractNumber?: string | null,
  contractType?: ContractType | null,
  contractState?: ContractState | null,
  vendorId?: string | null,
  commodityId?: string | null,
  quantity?: number | null,
  contractPrice?: number | null,
  salePrice?: number | null,
  terms?: string | null,
  weights?: string | null,
  basis?: string | null,
  remarks?: string | null,
  beginDate?: string | null,
  endDate?: string | null,
  dateSigned?: string | null,
  purchasedFrom?: string | null,
  soldTo?: string | null,
};

export type DeleteContractInput = {
  id?: string | null,
};

export type ModelTicketConditionInput = {
  contractId?: ModelIDInput | null,
  ticketDate?: ModelStringInput | null,
  fieldNum?: ModelStringInput | null,
  baleCount?: ModelFloatInput | null,
  ticketNumber?: ModelStringInput | null,
  ladingNumber?: ModelStringInput | null,
  driver?: ModelStringInput | null,
  truckNumber?: ModelStringInput | null,
  grossWeight?: ModelFloatInput | null,
  tareWeight?: ModelFloatInput | null,
  netWeight?: ModelFloatInput | null,
  netTons?: ModelFloatInput | null,
  and?: Array< ModelTicketConditionInput | null > | null,
  or?: Array< ModelTicketConditionInput | null > | null,
  not?: ModelTicketConditionInput | null,
};

export type UpdateTicketInput = {
  id: string,
  contractId?: string | null,
  ticketDate?: string | null,
  fieldNum?: string | null,
  baleCount?: number | null,
  ticketNumber?: string | null,
  ladingNumber?: string | null,
  driver?: string | null,
  truckNumber?: string | null,
  grossWeight?: number | null,
  tareWeight?: number | null,
  netWeight?: number | null,
  netTons?: number | null,
};

export type DeleteTicketInput = {
  id?: string | null,
};

export type ModelCompanyInfoFilterInput = {
  id?: ModelIDInput | null,
  companyName?: ModelStringInput | null,
  additionalName?: ModelStringInput | null,
  address1?: ModelStringInput | null,
  address2?: ModelStringInput | null,
  city?: ModelStringInput | null,
  state?: ModelStringInput | null,
  zipCode?: ModelIntInput | null,
  federalId?: ModelStringInput | null,
  telephoneNum?: ModelStringInput | null,
  faxNum?: ModelStringInput | null,
  and?: Array< ModelCompanyInfoFilterInput | null > | null,
  or?: Array< ModelCompanyInfoFilterInput | null > | null,
  not?: ModelCompanyInfoFilterInput | null,
};

export type ModelCommodityFilterInput = {
  id?: ModelIDInput | null,
  name?: ModelStringInput | null,
  calculateCode?: ModelIntInput | null,
  billingCode?: ModelIntInput | null,
  poundsPerBushel?: ModelIntInput | null,
  and?: Array< ModelCommodityFilterInput | null > | null,
  or?: Array< ModelCommodityFilterInput | null > | null,
  not?: ModelCommodityFilterInput | null,
};

export type ModelVendorFilterInput = {
  id?: ModelIDInput | null,
  vendorNumber?: ModelStringInput | null,
  companyReportName?: ModelStringInput | null,
  companyListingName?: ModelStringInput | null,
  address1?: ModelStringInput | null,
  address2?: ModelStringInput | null,
  city?: ModelStringInput | null,
  state?: ModelStringInput | null,
  zipCode?: ModelStringInput | null,
  telephoneNum?: ModelStringInput | null,
  attention?: ModelStringInput | null,
  prepayment?: ModelBooleanInput | null,
  prepaymentAmt?: ModelFloatInput | null,
  and?: Array< ModelVendorFilterInput | null > | null,
  or?: Array< ModelVendorFilterInput | null > | null,
  not?: ModelVendorFilterInput | null,
};

export type ModelContractFilterInput = {
  id?: ModelIDInput | null,
  contractNumber?: ModelStringInput | null,
  contractType?: ModelContractTypeInput | null,
  contractState?: ModelContractStateInput | null,
  vendorId?: ModelIDInput | null,
  commodityId?: ModelIDInput | null,
  quantity?: ModelFloatInput | null,
  contractPrice?: ModelFloatInput | null,
  salePrice?: ModelFloatInput | null,
  terms?: ModelStringInput | null,
  weights?: ModelStringInput | null,
  basis?: ModelStringInput | null,
  remarks?: ModelStringInput | null,
  beginDate?: ModelStringInput | null,
  endDate?: ModelStringInput | null,
  dateSigned?: ModelStringInput | null,
  purchasedFrom?: ModelStringInput | null,
  soldTo?: ModelStringInput | null,
  and?: Array< ModelContractFilterInput | null > | null,
  or?: Array< ModelContractFilterInput | null > | null,
  not?: ModelContractFilterInput | null,
};

export type ModelTicketFilterInput = {
  id?: ModelIDInput | null,
  contractId?: ModelIDInput | null,
  ticketDate?: ModelStringInput | null,
  fieldNum?: ModelStringInput | null,
  baleCount?: ModelFloatInput | null,
  ticketNumber?: ModelStringInput | null,
  ladingNumber?: ModelStringInput | null,
  driver?: ModelStringInput | null,
  truckNumber?: ModelStringInput | null,
  grossWeight?: ModelFloatInput | null,
  tareWeight?: ModelFloatInput | null,
  netWeight?: ModelFloatInput | null,
  netTons?: ModelFloatInput | null,
  and?: Array< ModelTicketFilterInput | null > | null,
  or?: Array< ModelTicketFilterInput | null > | null,
  not?: ModelTicketFilterInput | null,
};

export type ModelContractByStatusCompositeKeyConditionInput = {
  eq?: ModelContractByStatusCompositeKeyInput | null,
  le?: ModelContractByStatusCompositeKeyInput | null,
  lt?: ModelContractByStatusCompositeKeyInput | null,
  ge?: ModelContractByStatusCompositeKeyInput | null,
  gt?: ModelContractByStatusCompositeKeyInput | null,
  between?: Array< ModelContractByStatusCompositeKeyInput | null > | null,
  beginsWith?: ModelContractByStatusCompositeKeyInput | null,
};

export type ModelContractByStatusCompositeKeyInput = {
  contractType?: ContractType | null,
  endDate?: string | null,
};

export enum ModelSortDirection {
  ASC = "ASC",
  DESC = "DESC",
}


export type ModelStringKeyConditionInput = {
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
};

export type BatchAddVendorsMutationVariables = {
  vendors?: Array< CreateVendorInput | null > | null,
};

export type BatchAddVendorsMutation = {
  batchAddVendors:  Array< {
    __typename: "Vendor",
    id: string,
    vendorNumber: string,
    companyReportName: string | null,
    companyListingName: string,
    address1: string | null,
    address2: string | null,
    city: string | null,
    state: string | null,
    zipCode: string | null,
    telephoneNum: string | null,
    attention: string | null,
    prepayment: boolean,
    prepaymentAmt: number,
    createdAt: string,
    updatedAt: string,
  } | null > | null,
};

export type BatchAddContractsMutationVariables = {
  contracts?: Array< CreateContractInput | null > | null,
};

export type BatchAddContractsMutation = {
  batchAddContracts:  Array< {
    __typename: "Contract",
    id: string,
    contractNumber: string,
    contractType: ContractType,
    contractState: ContractState,
    vendorId: string,
    commodityId: string,
    contractTo:  {
      __typename: "Vendor",
      id: string,
      vendorNumber: string,
      companyReportName: string | null,
      companyListingName: string,
      address1: string | null,
      address2: string | null,
      city: string | null,
      state: string | null,
      zipCode: string | null,
      telephoneNum: string | null,
      attention: string | null,
      prepayment: boolean,
      prepaymentAmt: number,
      createdAt: string,
      updatedAt: string,
    },
    quantity: number,
    contractPrice: number,
    salePrice: number | null,
    terms: string | null,
    weights: string | null,
    basis: string | null,
    remarks: string | null,
    beginDate: string,
    endDate: string,
    dateSigned: string | null,
    purchasedFrom: string | null,
    soldTo: string | null,
    commodity:  {
      __typename: "Commodity",
      id: string,
      name: string,
      calculateCode: number,
      billingCode: number,
      poundsPerBushel: number | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    },
    createdAt: string,
    updatedAt: string,
  } | null > | null,
};

export type BatchAddTicketsMutationVariables = {
  tickets?: Array< CreateTicketInput | null > | null,
};

export type BatchAddTicketsMutation = {
  batchAddTickets:  Array< {
    __typename: "Ticket",
    id: string,
    contractId: string,
    contract:  {
      __typename: "Contract",
      id: string,
      contractNumber: string,
      contractType: ContractType,
      contractState: ContractState,
      vendorId: string,
      commodityId: string,
      contractTo:  {
        __typename: "Vendor",
        id: string,
        vendorNumber: string,
        companyReportName: string | null,
        companyListingName: string,
        address1: string | null,
        address2: string | null,
        city: string | null,
        state: string | null,
        zipCode: string | null,
        telephoneNum: string | null,
        attention: string | null,
        prepayment: boolean,
        prepaymentAmt: number,
        createdAt: string,
        updatedAt: string,
      },
      quantity: number,
      contractPrice: number,
      salePrice: number | null,
      terms: string | null,
      weights: string | null,
      basis: string | null,
      remarks: string | null,
      beginDate: string,
      endDate: string,
      dateSigned: string | null,
      purchasedFrom: string | null,
      soldTo: string | null,
      commodity:  {
        __typename: "Commodity",
        id: string,
        name: string,
        calculateCode: number,
        billingCode: number,
        poundsPerBushel: number | null,
        createdAt: string,
        updatedAt: string,
      },
      createdAt: string,
      updatedAt: string,
    },
    ticketDate: string,
    fieldNum: string | null,
    baleCount: number | null,
    ticketNumber: string | null,
    ladingNumber: string | null,
    driver: string | null,
    truckNumber: string | null,
    grossWeight: number | null,
    tareWeight: number | null,
    netWeight: number | null,
    netTons: number | null,
    createdAt: string,
    updatedAt: string,
  } | null > | null,
};

export type CreateCompanyInfoMutationVariables = {
  input: CreateCompanyInfoInput,
  condition?: ModelCompanyInfoConditionInput | null,
};

export type CreateCompanyInfoMutation = {
  createCompanyInfo:  {
    __typename: "CompanyInfo",
    id: string,
    companyName: string,
    additionalName: string | null,
    address1: string,
    address2: string | null,
    city: string,
    state: string,
    zipCode: number,
    federalId: string | null,
    telephoneNum: string | null,
    faxNum: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateCompanyInfoMutationVariables = {
  input: UpdateCompanyInfoInput,
  condition?: ModelCompanyInfoConditionInput | null,
};

export type UpdateCompanyInfoMutation = {
  updateCompanyInfo:  {
    __typename: "CompanyInfo",
    id: string,
    companyName: string,
    additionalName: string | null,
    address1: string,
    address2: string | null,
    city: string,
    state: string,
    zipCode: number,
    federalId: string | null,
    telephoneNum: string | null,
    faxNum: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteCompanyInfoMutationVariables = {
  input: DeleteCompanyInfoInput,
  condition?: ModelCompanyInfoConditionInput | null,
};

export type DeleteCompanyInfoMutation = {
  deleteCompanyInfo:  {
    __typename: "CompanyInfo",
    id: string,
    companyName: string,
    additionalName: string | null,
    address1: string,
    address2: string | null,
    city: string,
    state: string,
    zipCode: number,
    federalId: string | null,
    telephoneNum: string | null,
    faxNum: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateCommodityMutationVariables = {
  input: CreateCommodityInput,
  condition?: ModelCommodityConditionInput | null,
};

export type CreateCommodityMutation = {
  createCommodity:  {
    __typename: "Commodity",
    id: string,
    name: string,
    calculateCode: number,
    billingCode: number,
    poundsPerBushel: number | null,
    contracts:  {
      __typename: "ModelContractConnection",
      items:  Array< {
        __typename: "Contract",
        id: string,
        contractNumber: string,
        contractType: ContractType,
        contractState: ContractState,
        vendorId: string,
        commodityId: string,
        quantity: number,
        contractPrice: number,
        salePrice: number | null,
        terms: string | null,
        weights: string | null,
        basis: string | null,
        remarks: string | null,
        beginDate: string,
        endDate: string,
        dateSigned: string | null,
        purchasedFrom: string | null,
        soldTo: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateCommodityMutationVariables = {
  input: UpdateCommodityInput,
  condition?: ModelCommodityConditionInput | null,
};

export type UpdateCommodityMutation = {
  updateCommodity:  {
    __typename: "Commodity",
    id: string,
    name: string,
    calculateCode: number,
    billingCode: number,
    poundsPerBushel: number | null,
    contracts:  {
      __typename: "ModelContractConnection",
      items:  Array< {
        __typename: "Contract",
        id: string,
        contractNumber: string,
        contractType: ContractType,
        contractState: ContractState,
        vendorId: string,
        commodityId: string,
        quantity: number,
        contractPrice: number,
        salePrice: number | null,
        terms: string | null,
        weights: string | null,
        basis: string | null,
        remarks: string | null,
        beginDate: string,
        endDate: string,
        dateSigned: string | null,
        purchasedFrom: string | null,
        soldTo: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteCommodityMutationVariables = {
  input: DeleteCommodityInput,
  condition?: ModelCommodityConditionInput | null,
};

export type DeleteCommodityMutation = {
  deleteCommodity:  {
    __typename: "Commodity",
    id: string,
    name: string,
    calculateCode: number,
    billingCode: number,
    poundsPerBushel: number | null,
    contracts:  {
      __typename: "ModelContractConnection",
      items:  Array< {
        __typename: "Contract",
        id: string,
        contractNumber: string,
        contractType: ContractType,
        contractState: ContractState,
        vendorId: string,
        commodityId: string,
        quantity: number,
        contractPrice: number,
        salePrice: number | null,
        terms: string | null,
        weights: string | null,
        basis: string | null,
        remarks: string | null,
        beginDate: string,
        endDate: string,
        dateSigned: string | null,
        purchasedFrom: string | null,
        soldTo: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateVendorMutationVariables = {
  input: CreateVendorInput,
  condition?: ModelVendorConditionInput | null,
};

export type CreateVendorMutation = {
  createVendor:  {
    __typename: "Vendor",
    id: string,
    vendorNumber: string,
    companyReportName: string | null,
    companyListingName: string,
    address1: string | null,
    address2: string | null,
    city: string | null,
    state: string | null,
    zipCode: string | null,
    telephoneNum: string | null,
    attention: string | null,
    prepayment: boolean,
    prepaymentAmt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateVendorMutationVariables = {
  input: UpdateVendorInput,
  condition?: ModelVendorConditionInput | null,
};

export type UpdateVendorMutation = {
  updateVendor:  {
    __typename: "Vendor",
    id: string,
    vendorNumber: string,
    companyReportName: string | null,
    companyListingName: string,
    address1: string | null,
    address2: string | null,
    city: string | null,
    state: string | null,
    zipCode: string | null,
    telephoneNum: string | null,
    attention: string | null,
    prepayment: boolean,
    prepaymentAmt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteVendorMutationVariables = {
  input: DeleteVendorInput,
  condition?: ModelVendorConditionInput | null,
};

export type DeleteVendorMutation = {
  deleteVendor:  {
    __typename: "Vendor",
    id: string,
    vendorNumber: string,
    companyReportName: string | null,
    companyListingName: string,
    address1: string | null,
    address2: string | null,
    city: string | null,
    state: string | null,
    zipCode: string | null,
    telephoneNum: string | null,
    attention: string | null,
    prepayment: boolean,
    prepaymentAmt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateContractMutationVariables = {
  input: CreateContractInput,
  condition?: ModelContractConditionInput | null,
};

export type CreateContractMutation = {
  createContract:  {
    __typename: "Contract",
    id: string,
    contractNumber: string,
    contractType: ContractType,
    contractState: ContractState,
    vendorId: string,
    commodityId: string,
    contractTo:  {
      __typename: "Vendor",
      id: string,
      vendorNumber: string,
      companyReportName: string | null,
      companyListingName: string,
      address1: string | null,
      address2: string | null,
      city: string | null,
      state: string | null,
      zipCode: string | null,
      telephoneNum: string | null,
      attention: string | null,
      prepayment: boolean,
      prepaymentAmt: number,
      createdAt: string,
      updatedAt: string,
    },
    quantity: number,
    contractPrice: number,
    salePrice: number | null,
    terms: string | null,
    weights: string | null,
    basis: string | null,
    remarks: string | null,
    beginDate: string,
    endDate: string,
    dateSigned: string | null,
    purchasedFrom: string | null,
    soldTo: string | null,
    commodity:  {
      __typename: "Commodity",
      id: string,
      name: string,
      calculateCode: number,
      billingCode: number,
      poundsPerBushel: number | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    },
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateContractMutationVariables = {
  input: UpdateContractInput,
  condition?: ModelContractConditionInput | null,
};

export type UpdateContractMutation = {
  updateContract:  {
    __typename: "Contract",
    id: string,
    contractNumber: string,
    contractType: ContractType,
    contractState: ContractState,
    vendorId: string,
    commodityId: string,
    contractTo:  {
      __typename: "Vendor",
      id: string,
      vendorNumber: string,
      companyReportName: string | null,
      companyListingName: string,
      address1: string | null,
      address2: string | null,
      city: string | null,
      state: string | null,
      zipCode: string | null,
      telephoneNum: string | null,
      attention: string | null,
      prepayment: boolean,
      prepaymentAmt: number,
      createdAt: string,
      updatedAt: string,
    },
    quantity: number,
    contractPrice: number,
    salePrice: number | null,
    terms: string | null,
    weights: string | null,
    basis: string | null,
    remarks: string | null,
    beginDate: string,
    endDate: string,
    dateSigned: string | null,
    purchasedFrom: string | null,
    soldTo: string | null,
    commodity:  {
      __typename: "Commodity",
      id: string,
      name: string,
      calculateCode: number,
      billingCode: number,
      poundsPerBushel: number | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    },
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteContractMutationVariables = {
  input: DeleteContractInput,
  condition?: ModelContractConditionInput | null,
};

export type DeleteContractMutation = {
  deleteContract:  {
    __typename: "Contract",
    id: string,
    contractNumber: string,
    contractType: ContractType,
    contractState: ContractState,
    vendorId: string,
    commodityId: string,
    contractTo:  {
      __typename: "Vendor",
      id: string,
      vendorNumber: string,
      companyReportName: string | null,
      companyListingName: string,
      address1: string | null,
      address2: string | null,
      city: string | null,
      state: string | null,
      zipCode: string | null,
      telephoneNum: string | null,
      attention: string | null,
      prepayment: boolean,
      prepaymentAmt: number,
      createdAt: string,
      updatedAt: string,
    },
    quantity: number,
    contractPrice: number,
    salePrice: number | null,
    terms: string | null,
    weights: string | null,
    basis: string | null,
    remarks: string | null,
    beginDate: string,
    endDate: string,
    dateSigned: string | null,
    purchasedFrom: string | null,
    soldTo: string | null,
    commodity:  {
      __typename: "Commodity",
      id: string,
      name: string,
      calculateCode: number,
      billingCode: number,
      poundsPerBushel: number | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    },
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateTicketMutationVariables = {
  input: CreateTicketInput,
  condition?: ModelTicketConditionInput | null,
};

export type CreateTicketMutation = {
  createTicket:  {
    __typename: "Ticket",
    id: string,
    contractId: string,
    contract:  {
      __typename: "Contract",
      id: string,
      contractNumber: string,
      contractType: ContractType,
      contractState: ContractState,
      vendorId: string,
      commodityId: string,
      contractTo:  {
        __typename: "Vendor",
        id: string,
        vendorNumber: string,
        companyReportName: string | null,
        companyListingName: string,
        address1: string | null,
        address2: string | null,
        city: string | null,
        state: string | null,
        zipCode: string | null,
        telephoneNum: string | null,
        attention: string | null,
        prepayment: boolean,
        prepaymentAmt: number,
        createdAt: string,
        updatedAt: string,
      },
      quantity: number,
      contractPrice: number,
      salePrice: number | null,
      terms: string | null,
      weights: string | null,
      basis: string | null,
      remarks: string | null,
      beginDate: string,
      endDate: string,
      dateSigned: string | null,
      purchasedFrom: string | null,
      soldTo: string | null,
      commodity:  {
        __typename: "Commodity",
        id: string,
        name: string,
        calculateCode: number,
        billingCode: number,
        poundsPerBushel: number | null,
        createdAt: string,
        updatedAt: string,
      },
      createdAt: string,
      updatedAt: string,
    },
    ticketDate: string,
    fieldNum: string | null,
    baleCount: number | null,
    ticketNumber: string | null,
    ladingNumber: string | null,
    driver: string | null,
    truckNumber: string | null,
    grossWeight: number | null,
    tareWeight: number | null,
    netWeight: number | null,
    netTons: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateTicketMutationVariables = {
  input: UpdateTicketInput,
  condition?: ModelTicketConditionInput | null,
};

export type UpdateTicketMutation = {
  updateTicket:  {
    __typename: "Ticket",
    id: string,
    contractId: string,
    contract:  {
      __typename: "Contract",
      id: string,
      contractNumber: string,
      contractType: ContractType,
      contractState: ContractState,
      vendorId: string,
      commodityId: string,
      contractTo:  {
        __typename: "Vendor",
        id: string,
        vendorNumber: string,
        companyReportName: string | null,
        companyListingName: string,
        address1: string | null,
        address2: string | null,
        city: string | null,
        state: string | null,
        zipCode: string | null,
        telephoneNum: string | null,
        attention: string | null,
        prepayment: boolean,
        prepaymentAmt: number,
        createdAt: string,
        updatedAt: string,
      },
      quantity: number,
      contractPrice: number,
      salePrice: number | null,
      terms: string | null,
      weights: string | null,
      basis: string | null,
      remarks: string | null,
      beginDate: string,
      endDate: string,
      dateSigned: string | null,
      purchasedFrom: string | null,
      soldTo: string | null,
      commodity:  {
        __typename: "Commodity",
        id: string,
        name: string,
        calculateCode: number,
        billingCode: number,
        poundsPerBushel: number | null,
        createdAt: string,
        updatedAt: string,
      },
      createdAt: string,
      updatedAt: string,
    },
    ticketDate: string,
    fieldNum: string | null,
    baleCount: number | null,
    ticketNumber: string | null,
    ladingNumber: string | null,
    driver: string | null,
    truckNumber: string | null,
    grossWeight: number | null,
    tareWeight: number | null,
    netWeight: number | null,
    netTons: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteTicketMutationVariables = {
  input: DeleteTicketInput,
  condition?: ModelTicketConditionInput | null,
};

export type DeleteTicketMutation = {
  deleteTicket:  {
    __typename: "Ticket",
    id: string,
    contractId: string,
    contract:  {
      __typename: "Contract",
      id: string,
      contractNumber: string,
      contractType: ContractType,
      contractState: ContractState,
      vendorId: string,
      commodityId: string,
      contractTo:  {
        __typename: "Vendor",
        id: string,
        vendorNumber: string,
        companyReportName: string | null,
        companyListingName: string,
        address1: string | null,
        address2: string | null,
        city: string | null,
        state: string | null,
        zipCode: string | null,
        telephoneNum: string | null,
        attention: string | null,
        prepayment: boolean,
        prepaymentAmt: number,
        createdAt: string,
        updatedAt: string,
      },
      quantity: number,
      contractPrice: number,
      salePrice: number | null,
      terms: string | null,
      weights: string | null,
      basis: string | null,
      remarks: string | null,
      beginDate: string,
      endDate: string,
      dateSigned: string | null,
      purchasedFrom: string | null,
      soldTo: string | null,
      commodity:  {
        __typename: "Commodity",
        id: string,
        name: string,
        calculateCode: number,
        billingCode: number,
        poundsPerBushel: number | null,
        createdAt: string,
        updatedAt: string,
      },
      createdAt: string,
      updatedAt: string,
    },
    ticketDate: string,
    fieldNum: string | null,
    baleCount: number | null,
    ticketNumber: string | null,
    ladingNumber: string | null,
    driver: string | null,
    truckNumber: string | null,
    grossWeight: number | null,
    tareWeight: number | null,
    netWeight: number | null,
    netTons: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type GetCompanyInfoQueryVariables = {
  id: string,
};

export type GetCompanyInfoQuery = {
  getCompanyInfo:  {
    __typename: "CompanyInfo",
    id: string,
    companyName: string,
    additionalName: string | null,
    address1: string,
    address2: string | null,
    city: string,
    state: string,
    zipCode: number,
    federalId: string | null,
    telephoneNum: string | null,
    faxNum: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListCompanyInfosQueryVariables = {
  filter?: ModelCompanyInfoFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListCompanyInfosQuery = {
  listCompanyInfos:  {
    __typename: "ModelCompanyInfoConnection",
    items:  Array< {
      __typename: "CompanyInfo",
      id: string,
      companyName: string,
      additionalName: string | null,
      address1: string,
      address2: string | null,
      city: string,
      state: string,
      zipCode: number,
      federalId: string | null,
      telephoneNum: string | null,
      faxNum: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type GetCommodityQueryVariables = {
  id: string,
};

export type GetCommodityQuery = {
  getCommodity:  {
    __typename: "Commodity",
    id: string,
    name: string,
    calculateCode: number,
    billingCode: number,
    poundsPerBushel: number | null,
    contracts:  {
      __typename: "ModelContractConnection",
      items:  Array< {
        __typename: "Contract",
        id: string,
        contractNumber: string,
        contractType: ContractType,
        contractState: ContractState,
        vendorId: string,
        commodityId: string,
        quantity: number,
        contractPrice: number,
        salePrice: number | null,
        terms: string | null,
        weights: string | null,
        basis: string | null,
        remarks: string | null,
        beginDate: string,
        endDate: string,
        dateSigned: string | null,
        purchasedFrom: string | null,
        soldTo: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListCommoditysQueryVariables = {
  filter?: ModelCommodityFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListCommoditysQuery = {
  listCommoditys:  {
    __typename: "ModelCommodityConnection",
    items:  Array< {
      __typename: "Commodity",
      id: string,
      name: string,
      calculateCode: number,
      billingCode: number,
      poundsPerBushel: number | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type GetVendorQueryVariables = {
  id: string,
};

export type GetVendorQuery = {
  getVendor:  {
    __typename: "Vendor",
    id: string,
    vendorNumber: string,
    companyReportName: string | null,
    companyListingName: string,
    address1: string | null,
    address2: string | null,
    city: string | null,
    state: string | null,
    zipCode: string | null,
    telephoneNum: string | null,
    attention: string | null,
    prepayment: boolean,
    prepaymentAmt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListVendorsQueryVariables = {
  filter?: ModelVendorFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListVendorsQuery = {
  listVendors:  {
    __typename: "ModelVendorConnection",
    items:  Array< {
      __typename: "Vendor",
      id: string,
      vendorNumber: string,
      companyReportName: string | null,
      companyListingName: string,
      address1: string | null,
      address2: string | null,
      city: string | null,
      state: string | null,
      zipCode: string | null,
      telephoneNum: string | null,
      attention: string | null,
      prepayment: boolean,
      prepaymentAmt: number,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type GetContractQueryVariables = {
  id: string,
};

export type GetContractQuery = {
  getContract:  {
    __typename: "Contract",
    id: string,
    contractNumber: string,
    contractType: ContractType,
    contractState: ContractState,
    vendorId: string,
    commodityId: string,
    contractTo:  {
      __typename: "Vendor",
      id: string,
      vendorNumber: string,
      companyReportName: string | null,
      companyListingName: string,
      address1: string | null,
      address2: string | null,
      city: string | null,
      state: string | null,
      zipCode: string | null,
      telephoneNum: string | null,
      attention: string | null,
      prepayment: boolean,
      prepaymentAmt: number,
      createdAt: string,
      updatedAt: string,
    },
    quantity: number,
    contractPrice: number,
    salePrice: number | null,
    terms: string | null,
    weights: string | null,
    basis: string | null,
    remarks: string | null,
    beginDate: string,
    endDate: string,
    dateSigned: string | null,
    purchasedFrom: string | null,
    soldTo: string | null,
    commodity:  {
      __typename: "Commodity",
      id: string,
      name: string,
      calculateCode: number,
      billingCode: number,
      poundsPerBushel: number | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    },
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListContractsQueryVariables = {
  filter?: ModelContractFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListContractsQuery = {
  listContracts:  {
    __typename: "ModelContractConnection",
    items:  Array< {
      __typename: "Contract",
      id: string,
      contractNumber: string,
      contractType: ContractType,
      contractState: ContractState,
      vendorId: string,
      commodityId: string,
      contractTo:  {
        __typename: "Vendor",
        id: string,
        vendorNumber: string,
        companyReportName: string | null,
        companyListingName: string,
        address1: string | null,
        address2: string | null,
        city: string | null,
        state: string | null,
        zipCode: string | null,
        telephoneNum: string | null,
        attention: string | null,
        prepayment: boolean,
        prepaymentAmt: number,
        createdAt: string,
        updatedAt: string,
      },
      quantity: number,
      contractPrice: number,
      salePrice: number | null,
      terms: string | null,
      weights: string | null,
      basis: string | null,
      remarks: string | null,
      beginDate: string,
      endDate: string,
      dateSigned: string | null,
      purchasedFrom: string | null,
      soldTo: string | null,
      commodity:  {
        __typename: "Commodity",
        id: string,
        name: string,
        calculateCode: number,
        billingCode: number,
        poundsPerBushel: number | null,
        createdAt: string,
        updatedAt: string,
      },
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type GetTicketQueryVariables = {
  id: string,
};

export type GetTicketQuery = {
  getTicket:  {
    __typename: "Ticket",
    id: string,
    contractId: string,
    contract:  {
      __typename: "Contract",
      id: string,
      contractNumber: string,
      contractType: ContractType,
      contractState: ContractState,
      vendorId: string,
      commodityId: string,
      contractTo:  {
        __typename: "Vendor",
        id: string,
        vendorNumber: string,
        companyReportName: string | null,
        companyListingName: string,
        address1: string | null,
        address2: string | null,
        city: string | null,
        state: string | null,
        zipCode: string | null,
        telephoneNum: string | null,
        attention: string | null,
        prepayment: boolean,
        prepaymentAmt: number,
        createdAt: string,
        updatedAt: string,
      },
      quantity: number,
      contractPrice: number,
      salePrice: number | null,
      terms: string | null,
      weights: string | null,
      basis: string | null,
      remarks: string | null,
      beginDate: string,
      endDate: string,
      dateSigned: string | null,
      purchasedFrom: string | null,
      soldTo: string | null,
      commodity:  {
        __typename: "Commodity",
        id: string,
        name: string,
        calculateCode: number,
        billingCode: number,
        poundsPerBushel: number | null,
        createdAt: string,
        updatedAt: string,
      },
      createdAt: string,
      updatedAt: string,
    },
    ticketDate: string,
    fieldNum: string | null,
    baleCount: number | null,
    ticketNumber: string | null,
    ladingNumber: string | null,
    driver: string | null,
    truckNumber: string | null,
    grossWeight: number | null,
    tareWeight: number | null,
    netWeight: number | null,
    netTons: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListTicketsQueryVariables = {
  filter?: ModelTicketFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListTicketsQuery = {
  listTickets:  {
    __typename: "ModelTicketConnection",
    items:  Array< {
      __typename: "Ticket",
      id: string,
      contractId: string,
      contract:  {
        __typename: "Contract",
        id: string,
        contractNumber: string,
        contractType: ContractType,
        contractState: ContractState,
        vendorId: string,
        commodityId: string,
        quantity: number,
        contractPrice: number,
        salePrice: number | null,
        terms: string | null,
        weights: string | null,
        basis: string | null,
        remarks: string | null,
        beginDate: string,
        endDate: string,
        dateSigned: string | null,
        purchasedFrom: string | null,
        soldTo: string | null,
        createdAt: string,
        updatedAt: string,
      },
      ticketDate: string,
      fieldNum: string | null,
      baleCount: number | null,
      ticketNumber: string | null,
      ladingNumber: string | null,
      driver: string | null,
      truckNumber: string | null,
      grossWeight: number | null,
      tareWeight: number | null,
      netWeight: number | null,
      netTons: number | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type ContractsByStatusQueryVariables = {
  contractState?: ContractState | null,
  contractTypeEndDate?: ModelContractByStatusCompositeKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelContractFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ContractsByStatusQuery = {
  contractsByStatus:  {
    __typename: "ModelContractConnection",
    items:  Array< {
      __typename: "Contract",
      id: string,
      contractNumber: string,
      contractType: ContractType,
      contractState: ContractState,
      vendorId: string,
      commodityId: string,
      contractTo:  {
        __typename: "Vendor",
        id: string,
        vendorNumber: string,
        companyReportName: string | null,
        companyListingName: string,
        address1: string | null,
        address2: string | null,
        city: string | null,
        state: string | null,
        zipCode: string | null,
        telephoneNum: string | null,
        attention: string | null,
        prepayment: boolean,
        prepaymentAmt: number,
        createdAt: string,
        updatedAt: string,
      },
      quantity: number,
      contractPrice: number,
      salePrice: number | null,
      terms: string | null,
      weights: string | null,
      basis: string | null,
      remarks: string | null,
      beginDate: string,
      endDate: string,
      dateSigned: string | null,
      purchasedFrom: string | null,
      soldTo: string | null,
      commodity:  {
        __typename: "Commodity",
        id: string,
        name: string,
        calculateCode: number,
        billingCode: number,
        poundsPerBushel: number | null,
        createdAt: string,
        updatedAt: string,
      },
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type ContractsByVendorQueryVariables = {
  vendorId?: string | null,
  endDate?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelContractFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ContractsByVendorQuery = {
  contractsByVendor:  {
    __typename: "ModelContractConnection",
    items:  Array< {
      __typename: "Contract",
      id: string,
      contractNumber: string,
      contractType: ContractType,
      contractState: ContractState,
      vendorId: string,
      commodityId: string,
      contractTo:  {
        __typename: "Vendor",
        id: string,
        vendorNumber: string,
        companyReportName: string | null,
        companyListingName: string,
        address1: string | null,
        address2: string | null,
        city: string | null,
        state: string | null,
        zipCode: string | null,
        telephoneNum: string | null,
        attention: string | null,
        prepayment: boolean,
        prepaymentAmt: number,
        createdAt: string,
        updatedAt: string,
      },
      quantity: number,
      contractPrice: number,
      salePrice: number | null,
      terms: string | null,
      weights: string | null,
      basis: string | null,
      remarks: string | null,
      beginDate: string,
      endDate: string,
      dateSigned: string | null,
      purchasedFrom: string | null,
      soldTo: string | null,
      commodity:  {
        __typename: "Commodity",
        id: string,
        name: string,
        calculateCode: number,
        billingCode: number,
        poundsPerBushel: number | null,
        createdAt: string,
        updatedAt: string,
      },
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type ContractsByCommodityQueryVariables = {
  commodityId?: string | null,
  endDate?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelContractFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ContractsByCommodityQuery = {
  contractsByCommodity:  {
    __typename: "ModelContractConnection",
    items:  Array< {
      __typename: "Contract",
      id: string,
      contractNumber: string,
      contractType: ContractType,
      contractState: ContractState,
      vendorId: string,
      commodityId: string,
      contractTo:  {
        __typename: "Vendor",
        id: string,
        vendorNumber: string,
        companyReportName: string | null,
        companyListingName: string,
        address1: string | null,
        address2: string | null,
        city: string | null,
        state: string | null,
        zipCode: string | null,
        telephoneNum: string | null,
        attention: string | null,
        prepayment: boolean,
        prepaymentAmt: number,
        createdAt: string,
        updatedAt: string,
      },
      quantity: number,
      contractPrice: number,
      salePrice: number | null,
      terms: string | null,
      weights: string | null,
      basis: string | null,
      remarks: string | null,
      beginDate: string,
      endDate: string,
      dateSigned: string | null,
      purchasedFrom: string | null,
      soldTo: string | null,
      commodity:  {
        __typename: "Commodity",
        id: string,
        name: string,
        calculateCode: number,
        billingCode: number,
        poundsPerBushel: number | null,
        createdAt: string,
        updatedAt: string,
      },
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type ContractsByTypeQueryVariables = {
  contractType?: ContractType | null,
  endDate?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelContractFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ContractsByTypeQuery = {
  contractsByType:  {
    __typename: "ModelContractConnection",
    items:  Array< {
      __typename: "Contract",
      id: string,
      contractNumber: string,
      contractType: ContractType,
      contractState: ContractState,
      vendorId: string,
      commodityId: string,
      contractTo:  {
        __typename: "Vendor",
        id: string,
        vendorNumber: string,
        companyReportName: string | null,
        companyListingName: string,
        address1: string | null,
        address2: string | null,
        city: string | null,
        state: string | null,
        zipCode: string | null,
        telephoneNum: string | null,
        attention: string | null,
        prepayment: boolean,
        prepaymentAmt: number,
        createdAt: string,
        updatedAt: string,
      },
      quantity: number,
      contractPrice: number,
      salePrice: number | null,
      terms: string | null,
      weights: string | null,
      basis: string | null,
      remarks: string | null,
      beginDate: string,
      endDate: string,
      dateSigned: string | null,
      purchasedFrom: string | null,
      soldTo: string | null,
      commodity:  {
        __typename: "Commodity",
        id: string,
        name: string,
        calculateCode: number,
        billingCode: number,
        poundsPerBushel: number | null,
        createdAt: string,
        updatedAt: string,
      },
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type TicketsByContractQueryVariables = {
  contractId?: string | null,
  ticketDate?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelTicketFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type TicketsByContractQuery = {
  ticketsByContract:  {
    __typename: "ModelTicketConnection",
    items:  Array< {
      __typename: "Ticket",
      id: string,
      contractId: string,
      contract:  {
        __typename: "Contract",
        id: string,
        contractNumber: string,
        contractType: ContractType,
        contractState: ContractState,
        vendorId: string,
        commodityId: string,
        quantity: number,
        contractPrice: number,
        salePrice: number | null,
        terms: string | null,
        weights: string | null,
        basis: string | null,
        remarks: string | null,
        beginDate: string,
        endDate: string,
        dateSigned: string | null,
        purchasedFrom: string | null,
        soldTo: string | null,
        createdAt: string,
        updatedAt: string,
      },
      ticketDate: string,
      fieldNum: string | null,
      baleCount: number | null,
      ticketNumber: string | null,
      ladingNumber: string | null,
      driver: string | null,
      truckNumber: string | null,
      grossWeight: number | null,
      tareWeight: number | null,
      netWeight: number | null,
      netTons: number | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type OnCreateCompanyInfoSubscription = {
  onCreateCompanyInfo:  {
    __typename: "CompanyInfo",
    id: string,
    companyName: string,
    additionalName: string | null,
    address1: string,
    address2: string | null,
    city: string,
    state: string,
    zipCode: number,
    federalId: string | null,
    telephoneNum: string | null,
    faxNum: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateCompanyInfoSubscription = {
  onUpdateCompanyInfo:  {
    __typename: "CompanyInfo",
    id: string,
    companyName: string,
    additionalName: string | null,
    address1: string,
    address2: string | null,
    city: string,
    state: string,
    zipCode: number,
    federalId: string | null,
    telephoneNum: string | null,
    faxNum: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteCompanyInfoSubscription = {
  onDeleteCompanyInfo:  {
    __typename: "CompanyInfo",
    id: string,
    companyName: string,
    additionalName: string | null,
    address1: string,
    address2: string | null,
    city: string,
    state: string,
    zipCode: number,
    federalId: string | null,
    telephoneNum: string | null,
    faxNum: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateCommoditySubscription = {
  onCreateCommodity:  {
    __typename: "Commodity",
    id: string,
    name: string,
    calculateCode: number,
    billingCode: number,
    poundsPerBushel: number | null,
    contracts:  {
      __typename: "ModelContractConnection",
      items:  Array< {
        __typename: "Contract",
        id: string,
        contractNumber: string,
        contractType: ContractType,
        contractState: ContractState,
        vendorId: string,
        commodityId: string,
        quantity: number,
        contractPrice: number,
        salePrice: number | null,
        terms: string | null,
        weights: string | null,
        basis: string | null,
        remarks: string | null,
        beginDate: string,
        endDate: string,
        dateSigned: string | null,
        purchasedFrom: string | null,
        soldTo: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateCommoditySubscription = {
  onUpdateCommodity:  {
    __typename: "Commodity",
    id: string,
    name: string,
    calculateCode: number,
    billingCode: number,
    poundsPerBushel: number | null,
    contracts:  {
      __typename: "ModelContractConnection",
      items:  Array< {
        __typename: "Contract",
        id: string,
        contractNumber: string,
        contractType: ContractType,
        contractState: ContractState,
        vendorId: string,
        commodityId: string,
        quantity: number,
        contractPrice: number,
        salePrice: number | null,
        terms: string | null,
        weights: string | null,
        basis: string | null,
        remarks: string | null,
        beginDate: string,
        endDate: string,
        dateSigned: string | null,
        purchasedFrom: string | null,
        soldTo: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteCommoditySubscription = {
  onDeleteCommodity:  {
    __typename: "Commodity",
    id: string,
    name: string,
    calculateCode: number,
    billingCode: number,
    poundsPerBushel: number | null,
    contracts:  {
      __typename: "ModelContractConnection",
      items:  Array< {
        __typename: "Contract",
        id: string,
        contractNumber: string,
        contractType: ContractType,
        contractState: ContractState,
        vendorId: string,
        commodityId: string,
        quantity: number,
        contractPrice: number,
        salePrice: number | null,
        terms: string | null,
        weights: string | null,
        basis: string | null,
        remarks: string | null,
        beginDate: string,
        endDate: string,
        dateSigned: string | null,
        purchasedFrom: string | null,
        soldTo: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateVendorSubscription = {
  onCreateVendor:  {
    __typename: "Vendor",
    id: string,
    vendorNumber: string,
    companyReportName: string | null,
    companyListingName: string,
    address1: string | null,
    address2: string | null,
    city: string | null,
    state: string | null,
    zipCode: string | null,
    telephoneNum: string | null,
    attention: string | null,
    prepayment: boolean,
    prepaymentAmt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateVendorSubscription = {
  onUpdateVendor:  {
    __typename: "Vendor",
    id: string,
    vendorNumber: string,
    companyReportName: string | null,
    companyListingName: string,
    address1: string | null,
    address2: string | null,
    city: string | null,
    state: string | null,
    zipCode: string | null,
    telephoneNum: string | null,
    attention: string | null,
    prepayment: boolean,
    prepaymentAmt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteVendorSubscription = {
  onDeleteVendor:  {
    __typename: "Vendor",
    id: string,
    vendorNumber: string,
    companyReportName: string | null,
    companyListingName: string,
    address1: string | null,
    address2: string | null,
    city: string | null,
    state: string | null,
    zipCode: string | null,
    telephoneNum: string | null,
    attention: string | null,
    prepayment: boolean,
    prepaymentAmt: number,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateContractSubscription = {
  onCreateContract:  {
    __typename: "Contract",
    id: string,
    contractNumber: string,
    contractType: ContractType,
    contractState: ContractState,
    vendorId: string,
    commodityId: string,
    contractTo:  {
      __typename: "Vendor",
      id: string,
      vendorNumber: string,
      companyReportName: string | null,
      companyListingName: string,
      address1: string | null,
      address2: string | null,
      city: string | null,
      state: string | null,
      zipCode: string | null,
      telephoneNum: string | null,
      attention: string | null,
      prepayment: boolean,
      prepaymentAmt: number,
      createdAt: string,
      updatedAt: string,
    },
    quantity: number,
    contractPrice: number,
    salePrice: number | null,
    terms: string | null,
    weights: string | null,
    basis: string | null,
    remarks: string | null,
    beginDate: string,
    endDate: string,
    dateSigned: string | null,
    purchasedFrom: string | null,
    soldTo: string | null,
    commodity:  {
      __typename: "Commodity",
      id: string,
      name: string,
      calculateCode: number,
      billingCode: number,
      poundsPerBushel: number | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    },
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateContractSubscription = {
  onUpdateContract:  {
    __typename: "Contract",
    id: string,
    contractNumber: string,
    contractType: ContractType,
    contractState: ContractState,
    vendorId: string,
    commodityId: string,
    contractTo:  {
      __typename: "Vendor",
      id: string,
      vendorNumber: string,
      companyReportName: string | null,
      companyListingName: string,
      address1: string | null,
      address2: string | null,
      city: string | null,
      state: string | null,
      zipCode: string | null,
      telephoneNum: string | null,
      attention: string | null,
      prepayment: boolean,
      prepaymentAmt: number,
      createdAt: string,
      updatedAt: string,
    },
    quantity: number,
    contractPrice: number,
    salePrice: number | null,
    terms: string | null,
    weights: string | null,
    basis: string | null,
    remarks: string | null,
    beginDate: string,
    endDate: string,
    dateSigned: string | null,
    purchasedFrom: string | null,
    soldTo: string | null,
    commodity:  {
      __typename: "Commodity",
      id: string,
      name: string,
      calculateCode: number,
      billingCode: number,
      poundsPerBushel: number | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    },
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteContractSubscription = {
  onDeleteContract:  {
    __typename: "Contract",
    id: string,
    contractNumber: string,
    contractType: ContractType,
    contractState: ContractState,
    vendorId: string,
    commodityId: string,
    contractTo:  {
      __typename: "Vendor",
      id: string,
      vendorNumber: string,
      companyReportName: string | null,
      companyListingName: string,
      address1: string | null,
      address2: string | null,
      city: string | null,
      state: string | null,
      zipCode: string | null,
      telephoneNum: string | null,
      attention: string | null,
      prepayment: boolean,
      prepaymentAmt: number,
      createdAt: string,
      updatedAt: string,
    },
    quantity: number,
    contractPrice: number,
    salePrice: number | null,
    terms: string | null,
    weights: string | null,
    basis: string | null,
    remarks: string | null,
    beginDate: string,
    endDate: string,
    dateSigned: string | null,
    purchasedFrom: string | null,
    soldTo: string | null,
    commodity:  {
      __typename: "Commodity",
      id: string,
      name: string,
      calculateCode: number,
      billingCode: number,
      poundsPerBushel: number | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    },
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateTicketSubscription = {
  onCreateTicket:  {
    __typename: "Ticket",
    id: string,
    contractId: string,
    contract:  {
      __typename: "Contract",
      id: string,
      contractNumber: string,
      contractType: ContractType,
      contractState: ContractState,
      vendorId: string,
      commodityId: string,
      contractTo:  {
        __typename: "Vendor",
        id: string,
        vendorNumber: string,
        companyReportName: string | null,
        companyListingName: string,
        address1: string | null,
        address2: string | null,
        city: string | null,
        state: string | null,
        zipCode: string | null,
        telephoneNum: string | null,
        attention: string | null,
        prepayment: boolean,
        prepaymentAmt: number,
        createdAt: string,
        updatedAt: string,
      },
      quantity: number,
      contractPrice: number,
      salePrice: number | null,
      terms: string | null,
      weights: string | null,
      basis: string | null,
      remarks: string | null,
      beginDate: string,
      endDate: string,
      dateSigned: string | null,
      purchasedFrom: string | null,
      soldTo: string | null,
      commodity:  {
        __typename: "Commodity",
        id: string,
        name: string,
        calculateCode: number,
        billingCode: number,
        poundsPerBushel: number | null,
        createdAt: string,
        updatedAt: string,
      },
      createdAt: string,
      updatedAt: string,
    },
    ticketDate: string,
    fieldNum: string | null,
    baleCount: number | null,
    ticketNumber: string | null,
    ladingNumber: string | null,
    driver: string | null,
    truckNumber: string | null,
    grossWeight: number | null,
    tareWeight: number | null,
    netWeight: number | null,
    netTons: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateTicketSubscription = {
  onUpdateTicket:  {
    __typename: "Ticket",
    id: string,
    contractId: string,
    contract:  {
      __typename: "Contract",
      id: string,
      contractNumber: string,
      contractType: ContractType,
      contractState: ContractState,
      vendorId: string,
      commodityId: string,
      contractTo:  {
        __typename: "Vendor",
        id: string,
        vendorNumber: string,
        companyReportName: string | null,
        companyListingName: string,
        address1: string | null,
        address2: string | null,
        city: string | null,
        state: string | null,
        zipCode: string | null,
        telephoneNum: string | null,
        attention: string | null,
        prepayment: boolean,
        prepaymentAmt: number,
        createdAt: string,
        updatedAt: string,
      },
      quantity: number,
      contractPrice: number,
      salePrice: number | null,
      terms: string | null,
      weights: string | null,
      basis: string | null,
      remarks: string | null,
      beginDate: string,
      endDate: string,
      dateSigned: string | null,
      purchasedFrom: string | null,
      soldTo: string | null,
      commodity:  {
        __typename: "Commodity",
        id: string,
        name: string,
        calculateCode: number,
        billingCode: number,
        poundsPerBushel: number | null,
        createdAt: string,
        updatedAt: string,
      },
      createdAt: string,
      updatedAt: string,
    },
    ticketDate: string,
    fieldNum: string | null,
    baleCount: number | null,
    ticketNumber: string | null,
    ladingNumber: string | null,
    driver: string | null,
    truckNumber: string | null,
    grossWeight: number | null,
    tareWeight: number | null,
    netWeight: number | null,
    netTons: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteTicketSubscription = {
  onDeleteTicket:  {
    __typename: "Ticket",
    id: string,
    contractId: string,
    contract:  {
      __typename: "Contract",
      id: string,
      contractNumber: string,
      contractType: ContractType,
      contractState: ContractState,
      vendorId: string,
      commodityId: string,
      contractTo:  {
        __typename: "Vendor",
        id: string,
        vendorNumber: string,
        companyReportName: string | null,
        companyListingName: string,
        address1: string | null,
        address2: string | null,
        city: string | null,
        state: string | null,
        zipCode: string | null,
        telephoneNum: string | null,
        attention: string | null,
        prepayment: boolean,
        prepaymentAmt: number,
        createdAt: string,
        updatedAt: string,
      },
      quantity: number,
      contractPrice: number,
      salePrice: number | null,
      terms: string | null,
      weights: string | null,
      basis: string | null,
      remarks: string | null,
      beginDate: string,
      endDate: string,
      dateSigned: string | null,
      purchasedFrom: string | null,
      soldTo: string | null,
      commodity:  {
        __typename: "Commodity",
        id: string,
        name: string,
        calculateCode: number,
        billingCode: number,
        poundsPerBushel: number | null,
        createdAt: string,
        updatedAt: string,
      },
      createdAt: string,
      updatedAt: string,
    },
    ticketDate: string,
    fieldNum: string | null,
    baleCount: number | null,
    ticketNumber: string | null,
    ladingNumber: string | null,
    driver: string | null,
    truckNumber: string | null,
    grossWeight: number | null,
    tareWeight: number | null,
    netWeight: number | null,
    netTons: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};
