/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_E1hP9svTV",
    "aws_user_pools_web_client_id": "2maujet0aqq55pc18ljfjejiev",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://lslcoy6ohjbqflywmomuxzvfqi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
